import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
	return (
		<div className="min-h-screen bg-slate-800 text-white">
			<Head>
				<title>Aerial Game Studios</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 pt-20 pb-20 text-center">
				<b className="text-6xl">Aerial Game Studios</b>
			</div>
			<div className="text-center pt-20 pb-0">
				<b className="text-4xl">Who We Are</b>
			</div>
			<p className="text-center text-3xl ml-5 mr-5">Aerial Game Studios is just three people working on games. We make games about whatever we want, whenever we want. We like to have fun with random ideas that we turn into games.</p>
			<div className="text-center pt-20 pb-0">
				<b className="text-4xl">Our Games</b>
			</div>
			<div className="grid h-screen place-items-center grid-cols-2">
				<div className="max-w-sm rounded overflow-hidden shadow-lg">
					<Image width={427} height={384} className="w-full" src="/CountryballArena.png" alt="Countryball Arena"></Image>
					<div className="px-6 py-4">
						<div className=" text-white font-bold text-xl mb-2">Countryball Arena</div>
						<p className="text-white text-base">
						A fun, humorous thrill where you battle the game you&apos;re playing. Will be released on Steam.
						</p>
					</div>
					<div className="px-6 pt-4 pb-2">
						<span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">Exploring</span>
						<span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">Countryball</span>
						<span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">Unreleased</span>
					</div>
				</div>
				<div className="max-w-sm rounded overflow-hidden shadow-lg">
					<Image width={384} height={378} className="w-full" src="/8BitArmy.png" alt="8-Bit Army"></Image>
					<div className="px-6 py-4">
						<a className="text-cyan-500 font-bold text-xl mb-2" href="https://spookbyte.itch.io/8-bit-army">8-Bit Army (Solo Project by SpookG)</a>
						<p className="text-white text-base">
						An action-packed strategy game about storming an enemy castle.
						</p>
					</div>
					<div className="px-6 pt-4 pb-2">
						<span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">Strategy</span>
						<span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">Fighting</span>
						<span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">Demo</span>
					</div>
				</div>
			</div>
		</div>
	)
}

export default Home
